### ISSUE TITLE
Missing elements in new transformation for ALMA 2 LOBID

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1107]
**Aleph**

- [x] `"alternativeTitle.[]"` #1212
- [ ] `"containedIn.[].id"`
- [ ] `"bibliographicCitation"`
- [ ] `"containedIn.[].label"`
- [ ] `"containsExampleOfWork.[].creatorOfWork"`
- [ ] `"containsExampleOfWork.[].id"`
- [ ] `"containsExampleOfWork.[].label"`
- [ ] `"containsExampleOfWork.[].type.[]"`
- [ ] `"containsExampleOfWork.[].workNumbering"`
- [ ] `"contribution.[].agent.altLabel"`
- [ ] `"contribution.[].agent.altLabel.[]"`
- [ ] `"contribution.[].agent.dateOfBirth"`
- [ ] `"contribution.[].agent.dateOfBirthAndDeath"`
- [ ] `"contribution.[].agent.dateOfDeath"`
- [ ] `"contribution.[].agent.label.[]"`
- [ ] `"contribution.[].agent.source.id"`
- [ ] `"contribution.[].agent.source.label"`
- [ ] `"corporateBodyForTitle.[]"`
- [ ] `"coverage.[]"`
- [ ] `"describedBy.dateModified"`
- [ ] `"description.[].id"`
- [ ] `"description.[].label"`
- [x] `"doi.[]"` #1238 
- [ ] `"exampleOfWork.creatorOfWork"`
- [ ] `"exampleOfWork.id"`
- [ ] `"exampleOfWork.instrumentation.[]"`
- [ ] `"exampleOfWork.label"`
- [ ] `"exampleOfWork.type.[]"`
- [ ] `"exampleOfWork.workNumbering"`
- [ ] `"fulltextOnline.[].id"`
- [ ] `"fulltextOnline.[].label"`
- [x] `"hasItem.[].callNumber"` #1160 
- [x] `"hasItem.[].label"`
- [ ] `"hasItem.[].note"`
- [ ] `"hasItem.[].note.[]"`
- [x] `"inCollection.[].id"` #1114 
- [x] `"inCollection.[].label"`  #1114 
- [x] `"inCollection.[].type.[]"` #1114 
- [x] `"ismn.[]"` #1239 
- [x] `"isPartOf.[].hasSuperordinate.[].id"` #1179 
- [x] `"isPartOf.[].hasSuperordinate.[].label"`  #1179 
- [x] `"isPartOf.[].numbering"`  #1179 
- [x] `"isPartOf.[].type.[]"`  #1179 
- [ ] `"longitudeAndLatitude.[]"`
- [x] `"natureOfContent.[].gndIdentifier"`
- [x] `"natureOfContent.[].id"`
- [x] `"natureOfContent.[].label"`
- [ ] `"natureOfContent.[].source.id"`
- [ ] `"natureOfContent.[].source.label"`
- [ ] `"natureOfContent.[].type.[]"`
- [x] `"note.[]"`#1118
- [x] `"oclcNumber.[]"` #1113
- [ ] `"predecessor.[].id"`
- [ ] `"predecessor.[].label"`
- [ ] `"primaryForm.[].id"`
- [ ] `"primaryForm.[].label"`
- [ ] `"publication.[].description.[]"`
- [x] `"publication.[].endDate"`
- [ ] `"publication.[].frequency.[].id"`
- [ ] `"publication.[].frequency.[].label"`
- [x] `"publication.[].location.[]"`
- [ ] `"publication.[].note"`
- [x] `"publication.[].publicationHistory"`
- [x] `"publication.[].publishedBy.[]"`
- [x] `"related.[].label"`
- [x] `"responsibilityStatement.[]"` #1194
- [x] `"sameAs.[].id"` #1113
- [x] `"sameAs.[].label"` #1113
- [ ] `"seeAlso.[].id"`
- [ ] `"seeAlso.[].label"`
- [ ] `"shortTitle.[]"`
- [ ] `"similar.[].id"`
- [ ] `"similar.[].isbn.[]"`
- [ ] `"similar.[].label"`
- [ ] `"similar.[].note"`
- [ ] `"spatial.[].focus.geo.lat"`
- [ ] `"spatial.[].focus.geo.lon"`
- [ ] `"spatial.[].focus.id"`
- [ ] `"spatial.[].focus.label"`
- [ ] `"spatial.[].focus.type.[]"`
- [ ] `"spatial.[].id"`
- [ ] `"spatial.[].label"`
- [ ] `"spatial.[].notation"`
- [ ] `"spatial.[].source.id"`
- [ ] `"spatial.[].source.label"`
- [ ] `"spatial.[].type.[]"`
- [x] `"subjectAltLabel.[]"` #1190
- [ ] `"subject.[].componentList.[].altLabel"`
- [ ] `"subject.[].componentList.[].altLabel.[]"`
- [ ] `"subject.[].componentList.[].dateOfBirth"`
- [ ] `"subject.[].componentList.[].dateOfDeath"`
- [x] `"subject.[].componentList.[].gndIdentifier"` #1176
- [x] `"subject.[].componentList.[].id"` #1176
- [x] `"subject.[].componentList.[].label"` #1176
- [ ] `"subject.[].componentList.[].label.[]"` ???????
- [x] `"subject.[].componentList.[].source.id"` #1176
- [x] `"subject.[].componentList.[].source.label"` #1176
- [x] `"subject.[].componentList.[].type.[]"` #1176
- [ ] `"subject.[].id"`
- [x] `"subject.[].label"`
- [x] `"suject.[].notation"`
- [x] `"subject.[].source.id"`
- [ ] `"subject.[].source.[].label"`
- [x] `"subject.[].source.label"`
- [x] `"subject.[].type.[]"`
- [ ] `"successor.[].id"`
- [ ] `"successor.[].label"`
- [x] `"tableOfContents.[].id"`
- [ ] `"tableOfContents.[].label"`
- [x] `"thesisInformation.[]"` #1195
- [ ] `"titleKeyword.[]"`
- [x] `"titleOfSubSeries"` #1209
- [ ] `"urn.[]"`
- [x] `"zdbId"` #1113 

**Alma:**

- [ ] `"almaIdMMS"`
- [ ] `"contribution.[].conferenceDate"`
- [ ] `"contribution.[].conferenceIdentifier.[]"`
- [ ] `"contribution.[].conferenceName"`
- [ ] `"contribution.[].conferencePlace"`
- [ ] `"contribution.[].corporateBodyNameeNumber"`
- [ ] `"contribution.[].gndIdentifier"`
- [ ] `"IdentifierDOI.[]"`
- [ ] `"IdentifierZDB.[].identifierZDB"`
- [ ] `"TitleOther.title.[]"`

**Comment by TobiasNx** [comment]
@dr0i and I have compared the JSON-keys of 3000+ resources as transformed from ALMA and from Aleph and singled out the differences:

```bash

getAlmaIdsFromFileAndLookupLobid.sh

for i in $(ls *.json); do id=$(echo $i| cut -d '.' -f1); curl http://lobid.org/resources/$id > $id-aleph.json ; done

cat *-aleph.json|jq 'select(objects)|=[.] | map( paths(scalars) ) | map( map(select(numbers)="[]") | join(".")) | unique' > bigfile-aleph.json

cat bigfile-aleph.json | sort -u bigfile-aleph.json > bigfile-aleph._sort_u.json
```

**Comment by TobiasNx** [comment]
Since we are working with ALMA-Fix now. I should update this list for comparison ALMA-Fix and ALEPH-Morph.

**Comment by TobiasNx** [comment]
I compared all test files of ALEPH with ALMA-Fix to see which elements are still missing @acka47  could you have a look if there are still any left that are important for NWBIB or should be prioritized:

- [ ] containsExampleOfWork.[].creatorOfWork
- [ ] containsExampleOfWork.[].id
- [ ] containsExampleOfWork.[].instrumentation.[]
- [ ] containsExampleOfWork.[].label
- [ ] containsExampleOfWork.[].musicalKey
- [ ] containsExampleOfWork.[].type.[]
- [ ] containsExampleOfWork.[].workNumbering
- [ ] contribution.[].agent.altLabel
- [ ] contribution.[].agent.altLabel.[]
- [ ] contribution.[].agent.dateOfBirth
- [ ] contribution.[].agent.dateOfBirthAndDeath
- [ ] contribution.[].agent.dateOfDeath
- [ ] contribution.[].agent.label.[]
- [ ] contribution.[].agent.source.id
- [ ] contribution.[].agent.source.label
- [ ] corporateBodyForTitle.[]
- [ ] coverage.[]
- [ ] exampleOfWork.creatorOfWork
- [ ] exampleOfWork.id
- [ ] exampleOfWork.instrumentation.[]
- [ ] exampleOfWork.label
- [ ] exampleOfWork.type.[]
- [ ] hasItem.[].note.[]
- [ ] hasVersion.[].id
- [ ] hasVersion.[].label
- [ ] license.[].id
- [ ] license.[].label
- [ ] license.[].note.[]
- [ ] longitudeAndLatitude.[]
- [ ] publication.[].description.[]
- [ ] publication.[].frequency.[].id
- [ ] publication.[].frequency.[].label
- [ ] publication.[].location
- [ ] publication.[].note.[]
- [ ] publication.[].publishedBy
- [ ] related.[].note.[]
- [ ] seeAlso.[].id
- [ ] seeAlso.[].label
- [ ] shortTitle.[]
- [ ] similar.[].isbn.[]
- [ ] similar.[].note.[]
- [ ] subject.[].componentList.[].altLabel
- [ ] subject.[].componentList.[].altLabel.[]
- [ ] subject.[].componentList.[].dateOfBirth
- [ ] subject.[].componentList.[].dateOfBirthAndDeath
- [ ] subject.[].componentList.[].dateOfDeath
- [ ] successor.[].id
- [ ] successor.[].label
- [ ] titleKeyword.[]
- [ ] webPageArchived.[].id
- [ ] webPageArchived.[].label

**Comment by TobiasNx** [comment]
I close this ticket, since list in the initial post is not up to date anymore.

The new list is in #1475
