### ISSUE TITLE
Find testfiles for missing subject (Alma)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1222]
MARC-Feld | Inhalt

- [x] 600 | Nebeneintragung unter einem Schlagwort - Personenname #1273 
- [x] 610 | Nebeneintragung unter einem Schlagwort - Körperschaftsname #1221 
- [x] 611 | Nebeneintragung unter einem Schlagwort - Kongressname #1275 
- [x] 630 | Nebeneintragung unter einem Schlagwort - Bevorzugter Titel des Werks #1277 
- [ ] 647 | Nebeneintragung unter einem Schlagwort - Named Event
- [x] 648 | Nebeneintragung unter einem Schlagwort - Zeitschlagwort #1276 
- [x] 650 | Nebeneintragung unter einem Schlagwort - Sachschlagwort #1189 
- [x] 651 | Nebeneintragung unter einem Schlagwort - Geografischer Name #1274 
- [x] 653 | Indexierungsterm - nicht normiert #1220 
- [ ] 654 | Nebeneintragung unter einem Schlagwort - Normiertes Sachschlagwort
- [x] 655 | Indexierungsterm - Genre/Formschlagwort #1219 
- [ ] 656 | Indexierungsterm - Beruf 
- [ ] 657 | Indexierungsterm - Funktion
- [x] 658 | Indexierungsterm - Lehrplanziel #1278 
- [ ] 662 | Nebeneintragung unter einem Schlagwort - Hierarchischer Ortsname
- [x] 689 | RSWK - Schlagwortketten #1182 
- [ ] 69X | Local Subject Access Fields

**Comment by TobiasNx** [comment]
647, 654, 657, 662

found no test resources for these fields.

**Comment by dr0i** [comment]
In general it _is_ already possible to search those fields in XML data, just place the XML file to "src/test/resources/alma/almaMarcXmlTestFiles.xml.tar.bz2" and adapt the AlmaTest in https://github.com/hbz/lobid-resources/blob/a7794a371ddb0eee8425e1b0ff366e9c8d8ea5a5/src/test/java/org/lobid/resources/AlmaMarc21XmlToLobidJsonTest.java#L57 :

> private static final String PATTERN_TO_IDENTIFY_XML_RECORDS = ".*662\"";

But oh is this slow - while it is lighning fast when the field is at the beginning of an XML (like `001`) it takes about one second to filter out matches with `662"` . Did this nonetheless and stopped the program after 66k documents (20 h!) , no hits so far.

Not sure if I have to think about a faster way to find those XMLs or if we just wait for someone to point out it's missing by giving an example where we can work with. WDYT @TobiasNx ?

**Comment by dr0i** [comment]
Ah, when using the pattern without wildcard it's back to be ultra fast again :)
So, just  use e.g. `662` as pattern, not `.*662`.

**Comment by dr0i** [comment]
I couldn't also find any XML with the fields "647, 654, 657, 662" filtering the `update.xml.bgzf` containing 100k XML records using the OR pattern described at [wiki: How-to-find-particular-XML-records](https://github.com/hbz/lobid-resources/wiki/How-to-find-particular-XML-records).
I think we can close this issue then - WDYT @TobiasNx ?

**Comment by TobiasNx** [comment]
+1 For now we have our examples and corresponding tickets. So yes, thanks for finding a new faster way finding specific test files.
