### ISSUE TITLE
Missing elements in new transformation for ALMA 2 LOBID (new version)

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1475]
I compared all test files of ALEPH with ALMA-Fix to see which elements are still missing @acka47  could you have a look if there are still any left that are important for NWBIB or should be prioritized:

- [x] containsExampleOfWork.[].creatorOfWork #1499 
- [x] containsExampleOfWork.[].id #1499 
- [x] containsExampleOfWork.[].instrumentation.[] #1499 
- [x] containsExampleOfWork.[].label #1499 
- [x] containsExampleOfWork.[].musicalKey #1499 
- [x] containsExampleOfWork.[].type.[] #1499 
- [x] containsExampleOfWork.[].workNumbering #1499 
- [x] exampleOfWork.id #1499 
- [x] exampleOfWork.label #1499 
- [x] exampleOfWork.type.[] #1499
- [x] successor.[].id https://github.com/hbz/lobid-resources/pull/1498
- [x] successor.[].label https://github.com/hbz/lobid-resources/pull/1498
- [x] titleKeyword.[] https://github.com/hbz/lobid-resources/pull/1493
- [x] webPageArchived.[].id  :bangbang:  #1486 
- [x] webPageArchived.[].label  :bangbang: #1486  
- [x] license.[].id https://github.com/hbz/lobid-resources/issues/1491
- [x] license.[].label https://github.com/hbz/lobid-resources/issues/1491
- [x] license.[].note.[] https://github.com/hbz/lobid-resources/issues/1491
- [x] publication.[].frequency.[].id  :bangbang:  #1488  / #1484 
- [x] publication.[].frequency.[].label  :bangbang: #1488  / #1484 
- [x] publication.[].note.[]  :bangbang:  #1488  / #1484 
- [x] shortTitle.[] https://github.com/hbz/lobid-resources/pull/1493
- [ ] publication.[].description.[] :bangbang:  #1485 
- [ ] related.[].note.[]  :bangbang:  #1071 and #1501 
- [ ] subject.[].componentList.[].dateOfBirth https://github.com/hbz/lobid-resources/pull/1503
- [ ] subject.[].componentList.[].dateOfBirthAndDeath https://github.com/hbz/lobid-resources/pull/1503
- [ ] subject.[].componentList.[].dateOfDeath https://github.com/hbz/lobid-resources/pull/1503
- [ ] contribution.[].agent.dateOfBirth https://github.com/hbz/lobid-resources/pull/1503
- [ ] contribution.[].agent.dateOfBirthAndDeath https://github.com/hbz/lobid-resources/pull/1503
- [ ] contribution.[].agent.dateOfDeath https://github.com/hbz/lobid-resources/pull/1503
- [ ] similar.[].isbn.[]  https://github.com/hbz/lobid-resources/pull/1504
- [ ] similar.[].note.[]  https://github.com/hbz/lobid-resources/pull/1504
- [ ] subject.[].componentList.[].altLabel.[] https://github.com/hbz/lobid-resources/issues/1505  Needs to be done when elements are provided again
- [ ] contribution.[].agent.altLabel.[] https://github.com/hbz/lobid-resources/issues/1505 Needs to be done when elements are provided again
- [x] ~~seeAlso.[].id~~ => There seems to be no migrated data at the moment or no testfile with this. But I would keep it in the transformation.
- [x] ~~seeAlso.[].label~~  => There seems to be no migrated data at the moment or no testfile with this.  But I would keep it in the transformation. 
- [x] ~~hasItem.[].note.[]~~ => old hbz Dienstbibliothek, seems to be not supported anymore: https://github.com/hbz/lobid-resources/issues/1475#issuecomment-1301968123
- [x] ~~hasVersion.[].label~~ // we decided to stop `hasVersion` in its current form: #1367 and #1242 
- [x] ~~hasVersion.[].id~~ // we decided to stop `hasVersion` in its current form: #1367 and #1242 
- [x] ~~exampleOfWork.creatorOfWork~~ #1499  info is not migrated anymore to ALMA-Marc
- [x] ~~exampleOfWork.instrumentation.[]~~ #1499   info is not migrated anymore to ALMA-Marc
- [x] ~~publication.[].location~~  :bangbang:  => This element should be an array. It already exists.
- [x] ~~publication.[].publishedBy~~  :bangbang:  => This element should be an array. It already exists.
- [x] ~~coverage.[]~~ not needed anymore bc of NWBib enrichment of ZDB
- [x] ~~longitudeAndLatitude.[]~~ not needed anymore bc of NWBib enrichment of ZDB
- [x] ~~contribution.[].agent.source.id~~ since always GND Id source is not needed
- [x] ~~contribution.[].agent.label.[]~~ should be string
- [x] ~~subject.[].componentList.[].altLabel~~ (should be array)
- [x] ~~contribution.[].agent.altLabel~~  (should be array)
- [x] ~~corporateBodyForTitle.[]~~ :bangbang: #1482  => is not supported anymore.
- [x] ~~contribution.[].agent.source.label~~ since always GND Id source is not needed

_Originally posted by @TobiasNx in https://github.com/hbz/lobid-resources/issues/1107#issuecomment-1268562686_

**Comment by acka47** [comment]
Skimming through this, I identified these fields which should be implemented next:

- `corporateBodyForTitle.[]` which is important for display purposes I think

The publication fields are used in the NWBib UI (see [code](https://github.com/hbz/nwbib/blob/b475bccc52b149cf0ed73876beb154afd87fa764/app/views/tags/result_doc.scala.html#L24-L52)):

- publication.[].description.[]
- publication.[].frequency.[].id
- publication.[].frequency.[].label
- publication.[].location
- publication.[].note.[]
- publication.[].publishedBy

Also `related`, see [code](https://github.com/hbz/nwbib/blob/b475bccc52b149cf0ed73876beb154afd87fa764/app/views/tags/result_doc.scala.html#L210-L221):

- related

These had been important for Edoweb, see for context #152 & maybe also https://github.com/hbz/lobid-resources/issues/499:

- webPageArchived.[].id
- webPageArchived.[].label

**Comment by acka47** [comment]
Some fields aren't used anymore, e.g. `longitudeAndLatitude.[]` which must be a relict. We also should not need `coverage` in the future.

**Comment by acka47** [comment]
The `exampleOfWork` stuff seems to be used by UB Dortmund, see #516 and the encompassing issue #567, so this should be also on the list.

**Comment by acka47** [comment]
> I am not sure about the exampleOfWork information.

These should also be added but the properties listed in https://github.com/hbz/lobid-resources/issues/1475#issuecomment-1282075626 have priority over the exampleOfWork stuff.

**Comment by TobiasNx** [comment]
> The publication fields are used in the NWBib UI (see [code](https://github.com/hbz/nwbib/blob/b475bccc52b149cf0ed73876beb154afd87fa764/app/views/tags/result_doc.scala.html#L24-L52)):
> 
>     * publication.[].description.[]
> 
>     * publication.[].frequency.[].id
> 
>     * publication.[].frequency.[].label
> 
>     * publication.[].location
> 
>     * publication.[].note.[]
> 
>     * publication.[].publishedBy

It seems that 
* publication.[].publishedBy
* publication.[].location

are elements that should be arrays, they exist as array in ALMA-Fix. @acka47 I would drop them right?

**Comment by TobiasNx** [comment]
seeAlso.[].id
seeAlso.[].label
similar.[].isbn.[]
similar.[].note.[]
hasVersion.[].id
hasVersion.[].label

Before adding these the relations should finally defined and discussed, if similar and hasVersion should be droped. https://github.com/hbz/lobid-resources/issues/1400

**Comment by TobiasNx** [comment]
@dr0i could you give me an example for seeAlso in the current lobid-ressources I do not find any tests for that.

**Comment by TobiasNx** [comment]
Seems that:
- `seeAlso` is missing tests
- contributor and subject altLabels are a more complex issue which need the GND enrichment from ALMA which inactiv at the moment
- `hasVersion`: we decided to stop `hasVersion` in its current form: #1367 and #1242 
- `contribution.[].agent.label.[]`, `contribution.[].agent.source.id`, `contribution.[].agent.source.label`, `subject.[].componentList.[].altLabel` and `contribution.[].agent.altLabel` seem to be faulty elements
- `hasItem.[].note.[]` is missing tests

**Comment by acka47** [comment]
Re. `hasItem.note`: This was introduced with #167.

**Comment by dr0i** [comment]
Re ''seeAlso": I also can't find any examples, though I also couldn't make a comprehensive query. Just checked the 4 test files which formerly had that data, matched by:
```xml
<data source="655[-eu][ -1].[x3]">
 <regexp match="^[zZ][uU][sS]"/>
</data>
```
Seems to be gone from the catalog. I assume we can get rid of `seeAlso`.

**Comment by TobiasNx** [comment]
I close this issue since only some elements are missing, all of them are related to Pull Request or Tickets.
