### ISSUE TITLE
Contents of MAB field starting with URL are split into id and label

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#485]
- [x] [HT019353538](http://lobid.org/hbz01/HT019353538): Contains an URL as id and label instead of the abstract text. (edit @dr0i: couldn't find `abstract`)
- [x]  [HT014555885](http://lobid.org/hbz01/HT014555885): Contains an URL as id and label instead of a string in title. (edit @dr0i: fixed with #625
- [x]  [HT018851526](http://lobid.org/hbz01/HT018851526): Contains an URL as id and label instead of a string in publishedBy. (edit @dr0i: couldn't find `publishedBy`)
- [x]  [HT012990825](http://lobid.org/hbz01/HT012990825): Contains an URL as id and label instead of a string in note. (edit @dr0i: couldn't even find the resource - this is serious !)
- [x]  [TT000731778](http://lobid.org/hbz01/TT000731778): Contains an URL and rest of title as id and label instead of a string. (edit @dr0i: fixed with #625 see http://lobid.org/resources/TT000731778.json. But the frontend seems to have problems to render a view, see http://lobid.org/resources/TT000731778. Opened #633.).
- [x]  [TT001493152](http://lobid.org/hbz01/TT001493152): Contains an URL as id and label instead of a string in note. (edit @dr0i: hm , I see a prefix "Siehe:" plus the URL http://lobid.org/resources/TT001493152.json, so everything is OK?)
- [x]  [HT008068517](http://lobid.org/hbz01/HT008068517): Starts with an URL and thus is split up into id and label in otherTitleInformation.  Sub-issue of #482. ( (edit @dr0i: this does no more occur, at least for this resource. I think the URL is no more in the data.)

**Comment by ChristophEwertowski** [comment]
HT019353538: The definition of the used dcterms/abstract: `A summary of the resource.` Contains the link to the publisher which doesn't fit with dct/abstract. Should be put into `655e1.u` (URL in access over distance). 
HT014555885: `http://historycy.pl` from MAB 331 is put into title. The website isn't online anymore so we have to assume that there was no other title.
HT018851526: `http://www.primalamusica.com`. Wrongly cataloged. The publisher is `Prima la musica!` as can be seen here: http://www.primalamusica.com/contents/en-uk/about.html. The link should also be put in 655.
HT012990825: `http://link.springer.com/journal/10502`. Wrongly cataloged. Should be put into 655 or 334 (since it's the page of all issues of the journal).
TT000731778: `http://www.zeitung.de, Perspektiven der Online-Aktivitäten lokaler Tageszeitungen - oder: Das Wagnis Internet und der Verlust des Lokalen?` Is an article (see [bibliography of Mr. Höflich](https://www.uni-erfurt.de/kommunikationswissenschaft/personen/personenuebersicht/prof-dr-joachim-r-hoeflich/publikationen/)). Title correct.
TT001493152: `Http://www.zetamultimedia.com`. Typing error. Should be corrected to "http[...]". Then the note field would contain: "Siehe: http[...]"
HT008068517: ? http://www., e-mail: ratgeber@aulis`. Cataloging error. E-Mail can be put into MAB `655a1.a` or maybe 411.

So only the two resources which contain an URL in their title (HT014555885 and TT000731778) will remain after the corrections.

**Comment by dr0i** [comment]
@ChristophEwertowski  :Don't understand what I shall do.

**Comment by ChristophEwertowski** [comment]
I think the task is to turn off the default for `title` which recognises something as an URL and adds a label. Both resources start with an URL and thus have an id and label in their title instead of a string.

**Comment by dr0i** [comment]
@ChristophEwertowski I've made a list and went through it  (see above) and added some comments. Please check it out.

**Comment by ChristophEwertowski** [comment]
HT019353538 and HT018851526: I already corrected it in Aleph. So I ticked it off now.

**Comment by dr0i** [comment]
Since HT012990825 is indexed now with the resolving of #670 this issue is resolved.
Closing.
